spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8080}
          predicates:
            - Path=/auth/**

        - id: product-service
          uri: ${PRODUCT_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/products/**,/categories/**,/admin/**

        - id: cart-service
          uri: ${CART_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/cart/**

        - id: order-service
          uri: ${ORDER_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/orders/**

        - id: payment-service
          uri: ${PAYMENT_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/payments/**

        - id: inventory-service
          uri: ${INVENTORY_SERVICE_URL:http://localhost:8086}
          predicates:
            - Path=/inventory/**

        - id: notification-service
          uri: ${NOTIFICATION_SERVICE_URL:http://localhost:8087}
          predicates:
            - Path=/notifications/**

server:
  port: ${SERVER_PORT:8085}

app:
  security:
    jwt-secret: ${JWT_SECRET:this-is-my-super-secret-key-which-is-very-long-123456}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
