spring:
  application:
    name: product-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/productdb}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    open-in-view: false
  elasticsearch:
    uris: ${ELASTICSEARCH_URI:http://localhost:9200}
  data:
    elasticsearch:
      repositories:
        enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.karn01.productservice.event"
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

file:
  upload-dir: ${FILE_UPLOAD_DIR:uploads}

server:
  port: ${SERVER_PORT:8081}

app:
  kafka:
    topics:
      order-created: ${ORDER_CREATED_TOPIC:cloth.order.created}
      order-processed: ${ORDER_PROCESSED_TOPIC:cloth.order.processed}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
